from distutils.core import setup

setup(
    name='alexa-gst-skill',
    version='0.1.0',
    packages=['env.Lib.distutils', 'env.Lib.encodings', 'env.Lib.site-packages.bs4', 'env.Lib.site-packages.bs4.tests',
              'env.Lib.site-packages.bs4.builder', 'env.Lib.site-packages.pip', 'env.Lib.site-packages.pip.req',
              'env.Lib.site-packages.pip.vcs', 'env.Lib.site-packages.pip.utils', 'env.Lib.site-packages.pip.compat',
              'env.Lib.site-packages.pip.models', 'env.Lib.site-packages.pip._vendor',
              'env.Lib.site-packages.pip._vendor.distlib', 'env.Lib.site-packages.pip._vendor.distlib._backport',
              'env.Lib.site-packages.pip._vendor.colorama', 'env.Lib.site-packages.pip._vendor.html5lib',
              'env.Lib.site-packages.pip._vendor.html5lib._trie', 'env.Lib.site-packages.pip._vendor.html5lib.filters',
              'env.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'env.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'env.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'env.Lib.site-packages.pip._vendor.lockfile',
              'env.Lib.site-packages.pip._vendor.progress', 'env.Lib.site-packages.pip._vendor.requests',
              'env.Lib.site-packages.pip._vendor.requests.packages',
              'env.Lib.site-packages.pip._vendor.requests.packages.chardet',
              'env.Lib.site-packages.pip._vendor.requests.packages.urllib3',
              'env.Lib.site-packages.pip._vendor.requests.packages.urllib3.util',
              'env.Lib.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'env.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'env.Lib.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.pip._vendor.packaging', 'env.Lib.site-packages.pip._vendor.cachecontrol',
              'env.Lib.site-packages.pip._vendor.cachecontrol.caches', 'env.Lib.site-packages.pip._vendor.webencodings',
              'env.Lib.site-packages.pip._vendor.pkg_resources', 'env.Lib.site-packages.pip.commands',
              'env.Lib.site-packages.pip.operations', 'env.Lib.site-packages.rsa', 'env.Lib.site-packages.cffi',
              'env.Lib.site-packages.enum', 'env.Lib.site-packages.html', 'env.Lib.site-packages.http',
              'env.Lib.site-packages.idna', 'env.Lib.site-packages.past', 'env.Lib.site-packages.past.tests',
              'env.Lib.site-packages.past.types', 'env.Lib.site-packages.past.utils',
              'env.Lib.site-packages.past.builtins', 'env.Lib.site-packages.past.translation',
              'env.Lib.site-packages.pytz', 'env.Lib.site-packages.tqdm', 'env.Lib.site-packages.yaml',
              'env.Lib.site-packages.babel', 'env.Lib.site-packages.babel.messages',
              'env.Lib.site-packages.babel.localtime', 'env.Lib.site-packages.boto3', 'env.Lib.site-packages.boto3.s3',
              'env.Lib.site-packages.boto3.ec2', 'env.Lib.site-packages.boto3.docs',
              'env.Lib.site-packages.boto3.dynamodb', 'env.Lib.site-packages.boto3.resources',
              'env.Lib.site-packages.click', 'env.Lib.site-packages.flask', 'env.Lib.site-packages.flask.ext',
              'env.Lib.site-packages.hjson', 'env.Lib.site-packages.hjson.tests', 'env.Lib.site-packages.kappa',
              'env.Lib.site-packages.kappa.scripts', 'env.Lib.site-packages.kappa.event_source',
              'env.Lib.site-packages.queue', 'env.Lib.site-packages.webob', 'env.Lib.site-packages.wheel',
              'env.Lib.site-packages.wheel.tool', 'env.Lib.site-packages.wheel.signatures',
              'env.Lib.site-packages.zappa', 'env.Lib.site-packages.zappa.ext', 'env.Lib.site-packages.awscli',
              'env.Lib.site-packages.awscli.customizations', 'env.Lib.site-packages.awscli.customizations.s3',
              'env.Lib.site-packages.awscli.customizations.s3.syncstrategy',
              'env.Lib.site-packages.awscli.customizations.ec2', 'env.Lib.site-packages.awscli.customizations.emr',
              'env.Lib.site-packages.awscli.customizations.gamelift',
              'env.Lib.site-packages.awscli.customizations.configure',
              'env.Lib.site-packages.awscli.customizations.cloudtrail',
              'env.Lib.site-packages.awscli.customizations.codedeploy',
              'env.Lib.site-packages.awscli.customizations.datapipeline',
              'env.Lib.site-packages.awscli.customizations.configservice',
              'env.Lib.site-packages.awscli.customizations.cloudformation',
              'env.Lib.site-packages.awscli.customizations.servicecatalog', 'env.Lib.site-packages.future',
              'env.Lib.site-packages.future.moves', 'env.Lib.site-packages.future.moves.dbm',
              'env.Lib.site-packages.future.moves.html', 'env.Lib.site-packages.future.moves.http',
              'env.Lib.site-packages.future.moves.test', 'env.Lib.site-packages.future.moves.urllib',
              'env.Lib.site-packages.future.moves.xmlrpc', 'env.Lib.site-packages.future.moves.tkinter',
              'env.Lib.site-packages.future.tests', 'env.Lib.site-packages.future.types',
              'env.Lib.site-packages.future.utils', 'env.Lib.site-packages.future.builtins',
              'env.Lib.site-packages.future.backports', 'env.Lib.site-packages.future.backports.html',
              'env.Lib.site-packages.future.backports.http', 'env.Lib.site-packages.future.backports.test',
              'env.Lib.site-packages.future.backports.email', 'env.Lib.site-packages.future.backports.email.mime',
              'env.Lib.site-packages.future.backports.urllib', 'env.Lib.site-packages.future.backports.xmlrpc',
              'env.Lib.site-packages.future.standard_library', 'env.Lib.site-packages.jinja2',
              'env.Lib.site-packages.pyasn1', 'env.Lib.site-packages.pyasn1.type', 'env.Lib.site-packages.pyasn1.codec',
              'env.Lib.site-packages.pyasn1.codec.ber', 'env.Lib.site-packages.pyasn1.codec.cer',
              'env.Lib.site-packages.pyasn1.codec.der', 'env.Lib.site-packages.pyasn1.codec.native',
              'env.Lib.site-packages.pyasn1.compat', 'env.Lib.site-packages.sphinx', 'env.Lib.site-packages.sphinx.ext',
              'env.Lib.site-packages.sphinx.ext.napoleon', 'env.Lib.site-packages.sphinx.ext.autosummary',
              'env.Lib.site-packages.sphinx.util', 'env.Lib.site-packages.sphinx.locale',
              'env.Lib.site-packages.sphinx.pycode', 'env.Lib.site-packages.sphinx.pycode.pgen2',
              'env.Lib.site-packages.sphinx.search', 'env.Lib.site-packages.sphinx.domains',
              'env.Lib.site-packages.sphinx.writers', 'env.Lib.site-packages.sphinx.builders',
              'env.Lib.site-packages.sphinx.directives', 'env.Lib.site-packages.sphinx.transforms',
              'env.Lib.site-packages.sphinx.websupport', 'env.Lib.site-packages.sphinx.websupport.search',
              'env.Lib.site-packages.sphinx.websupport.storage', 'env.Lib.site-packages.sphinx.environment',
              'env.Lib.site-packages.sphinx.environment.managers', 'env.Lib.site-packages.winreg',
              'env.Lib.site-packages.xmlrpc', 'env.Lib.site-packages._thread', 'env.Lib.site-packages.autodoc',
              'env.Lib.site-packages.copyreg', 'env.Lib.site-packages.OpenSSL', 'env.Lib.site-packages.placebo',
              'env.Lib.site-packages.reprlib', 'env.Lib.site-packages.slugify', 'env.Lib.site-packages.tkinter',
              'env.Lib.site-packages.webtest', 'env.Lib.site-packages.botocore', 'env.Lib.site-packages.botocore.docs',
              'env.Lib.site-packages.botocore.docs.bcdoc', 'env.Lib.site-packages.botocore.vendored',
              'env.Lib.site-packages.botocore.vendored.requests',
              'env.Lib.site-packages.botocore.vendored.requests.packages',
              'env.Lib.site-packages.botocore.vendored.requests.packages.chardet',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3.util',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3.contrib',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3.packages',
              'env.Lib.site-packages.botocore.vendored.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.builtins', 'env.Lib.site-packages.colorama', 'env.Lib.site-packages.dateutil',
              'env.Lib.site-packages.dateutil.tz', 'env.Lib.site-packages.dateutil.zoneinfo',
              'env.Lib.site-packages.docutils', 'env.Lib.site-packages.docutils.utils',
              'env.Lib.site-packages.docutils.utils.math', 'env.Lib.site-packages.docutils.parsers',
              'env.Lib.site-packages.docutils.parsers.rst', 'env.Lib.site-packages.docutils.parsers.rst.languages',
              'env.Lib.site-packages.docutils.parsers.rst.directives', 'env.Lib.site-packages.docutils.readers',
              'env.Lib.site-packages.docutils.writers', 'env.Lib.site-packages.docutils.writers.xetex',
              'env.Lib.site-packages.docutils.writers.latex2e', 'env.Lib.site-packages.docutils.writers.odf_odt',
              'env.Lib.site-packages.docutils.writers.s5_html', 'env.Lib.site-packages.docutils.writers.pep_html',
              'env.Lib.site-packages.docutils.writers.html4css1',
              'env.Lib.site-packages.docutils.writers.html5_polyglot', 'env.Lib.site-packages.docutils.languages',
              'env.Lib.site-packages.docutils.transforms', 'env.Lib.site-packages.examples',
              'env.Lib.site-packages.jmespath', 'env.Lib.site-packages.pygments',
              'env.Lib.site-packages.pygments.lexers', 'env.Lib.site-packages.pygments.styles',
              'env.Lib.site-packages.pygments.filters', 'env.Lib.site-packages.pygments.formatters',
              'env.Lib.site-packages.requests', 'env.Lib.site-packages.requests.packages',
              'env.Lib.site-packages.requests.packages.idna', 'env.Lib.site-packages.requests.packages.chardet',
              'env.Lib.site-packages.requests.packages.urllib3', 'env.Lib.site-packages.requests.packages.urllib3.util',
              'env.Lib.site-packages.requests.packages.urllib3.contrib',
              'env.Lib.site-packages.requests.packages.urllib3.packages',
              'env.Lib.site-packages.requests.packages.urllib3.packages.backports',
              'env.Lib.site-packages.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.waitress', 'env.Lib.site-packages.waitress.tests',
              'env.Lib.site-packages.waitress.tests.fixtureapps', 'env.Lib.site-packages.werkzeug',
              'env.Lib.site-packages.werkzeug.debug', 'env.Lib.site-packages.werkzeug.contrib',
              'env.Lib.site-packages.alabaster', 'env.Lib.site-packages.aniso8601', 'env.Lib.site-packages.flask_ask',
              'env.Lib.site-packages.imagesize', 'env.Lib.site-packages.pycparser',
              'env.Lib.site-packages.pycparser.ply', 'env.Lib.site-packages.unidecode',
              'env.Lib.site-packages.concurrent', 'env.Lib.site-packages.concurrent.futures',
              'env.Lib.site-packages.durationpy', 'env.Lib.site-packages.markupsafe',
              'env.Lib.site-packages.s3transfer', 'env.Lib.site-packages.setuptools',
              'env.Lib.site-packages.setuptools.extern', 'env.Lib.site-packages.setuptools.command',
              'env.Lib.site-packages._markupbase', 'env.Lib.site-packages.argcomplete',
              'env.Lib.site-packages.libfuturize', 'env.Lib.site-packages.libfuturize.fixes',
              'env.Lib.site-packages.troposphere', 'env.Lib.site-packages.troposphere.helpers',
              'env.Lib.site-packages.troposphere.openstack', 'env.Lib.site-packages.cryptography',
              'env.Lib.site-packages.cryptography.x509', 'env.Lib.site-packages.cryptography.hazmat',
              'env.Lib.site-packages.cryptography.hazmat.backends',
              'env.Lib.site-packages.cryptography.hazmat.backends.openssl',
              'env.Lib.site-packages.cryptography.hazmat.backends.commoncrypto',
              'env.Lib.site-packages.cryptography.hazmat.bindings',
              'env.Lib.site-packages.cryptography.hazmat.bindings.openssl',
              'env.Lib.site-packages.cryptography.hazmat.bindings.commoncrypto',
              'env.Lib.site-packages.cryptography.hazmat.primitives',
              'env.Lib.site-packages.cryptography.hazmat.primitives.kdf',
              'env.Lib.site-packages.cryptography.hazmat.primitives.ciphers',
              'env.Lib.site-packages.cryptography.hazmat.primitives.twofactor',
              'env.Lib.site-packages.cryptography.hazmat.primitives.asymmetric',
              'env.Lib.site-packages.cryptography.hazmat.primitives.interfaces', 'env.Lib.site-packages.socketserver',
              'env.Lib.site-packages._dummy_thread', 'env.Lib.site-packages.libpasteurize',
              'env.Lib.site-packages.libpasteurize.fixes', 'env.Lib.site-packages.pkg_resources',
              'env.Lib.site-packages.pkg_resources.extern', 'env.Lib.site-packages.pkg_resources._vendor',
              'env.Lib.site-packages.pkg_resources._vendor.packaging', 'env.Lib.site-packages.requestlogger',
              'env.Lib.site-packages.lambda_packages', 'env.Lib.site-packages.snowballstemmer',
              'env.Lib.site-packages.sphinx_rtd_theme', 'tests'],
    url='',
    license='',
    author='Mahesh Jadhav',
    author_email='mahesh.jadhav@capgemini.com',
    description='GST Alexa skill service'
)
